bookmarking; adding validations

diff --git a/baste b/baste
--- a/baste
+++ b/baste
@@ -2,19 +2,25 @@
 # This script was generated by bashly (https://github.com/DannyBen/bashly)
 # Modifying it manually is not recommended
 
+# :script.bash3_bouncer
+if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+  printf "bash version 4 or higher is required\n"
+  exit 1
+fi
+
 # :command.root_command
 root_command() {
   # :src/root_command.sh
   requires curl
   requires git
   requires jq
-  
+
   if [[ "${OSTYPE}" == "darwin"* ]]; then
     requires pbpaste
   else
     requires xclip
   fi
-  
+
   : "${GITHUB_TOKEN:=}"
   if [[ "${args[--token]}" ]]; then               # First, --token flag takes precedence.
     token="${args[--token]}"
@@ -25,7 +31,7 @@ root_command() {
   else
     err 'you must specifiy a valid token before posting; exiting ...'
   fi
-  
+
   content="${args[--content]}"
   if [[ "${args[--file]}" ]]; then
     if ! test -f "${args[--file]}"; then
@@ -35,15 +41,15 @@ root_command() {
    elif [[ "${args[--clipboard]}" ]]; then
     [[ "${OSTYPE}" == "darwin"* ]] && content=$(pbpaste) || content=$(xclip -o -selection clipboard)
   fi
-  
+
   if read -t 0; then
     read -r content
   fi
-  
+
   [[ ! "${content}" ]] && err 'you must provide some kind of content to post; exiting ...'
-  
+
   [[ "${args[--public]}" ]] && public="true" || public="false"
-  
+
   payload=$(
     jq -n \
       --arg     description "${args[--description]}" \
@@ -52,7 +58,8 @@ root_command() {
       --arg     content     "${content}"             \
       --argjson public      ${public}                \
       '{
-        description: $description, 
+        description: $description,
+
         public: $public,
         files: {
           "\($name).\($extension)": {
@@ -61,23 +68,23 @@ root_command() {
         }
       }'
   )
-  
+
   response=$(
-    curl -s -X POST https://api.github.com/gists \
+    curl -sw "%{http_code}" https://api.github.com/gists \
     -H "Accept: application/vnd.github.v3+json" \
     -H "Authorization: token ${token}" \
-    -d "${payload}"
+    -d "${payload}" \
   )
-  
-  url=$(echo "${response}" | jq -r '.html_url')
-  [[ "${url}" == 'null' ]] && err "$(echo "${response}" | jq -r '.message' | tr -d '\n\t')"
-  
-  if [[ "${args[--skip-short-url]}" ]]; then
-    echo "${url}"
-    exit 0
+
+  code="${response##*$'\n'}"
+  body="${response%$'\n'*}"
+
+  if [[ "${code}" != "201" ]]; then
+    message=$(echo "${body}" | jq -r '.message')
+    err "error from gist.github.com: ${message}; exiting ..."
   fi
-  
-  curl -is https://git.io -F "url=${url}" | awk -v FS=": " '/^Location/{print $2}'
+
+  echo "${body}" | jq -r '.html_url'
 }
 
 # :command.version_command
@@ -88,11 +95,13 @@ version_command() {
 # :command.usage
 baste_usage() {
   if [[ -n $long_usage ]]; then
-    printf "baste - A paste bin tool written in Bash for quickly creating Gists.\n"
-    echo 
+    printf "baste - A paste bin tool written in Bash for quickly creating gists.\n"
+    echo
+
   else
-    printf "baste - A paste bin tool written in Bash for quickly creating Gists.\n"
-    echo 
+    printf "baste - A paste bin tool written in Bash for quickly creating gists.\n"
+    echo
+
   fi
 
   printf "Usage:\n"
@@ -113,46 +122,46 @@ baste_usage() {
     # :command.usage_flags
     # :flag.usage
     echo "  --description, -d DESCRIPTION"
-    printf "    A brief description of your Gist.\n"
+    printf "    A brief description of your gist.\n"
     echo
-    
+
     # :flag.usage
     echo "  --name, -n NAME"
-    printf "    The file name of your Gist.\n"
+    printf "    The file name of your gist.\n"
     printf "    Default: gistfile1\n"
     echo
-    
+
     # :flag.usage
     echo "  --content, -c CONTENT"
-    printf "    The content of your Gist.\n"
+    printf "    The content of your gist.\n"
     echo
-    
+
     # :flag.usage
     echo "  --public, -p"
-    printf "    Determines whether your Gist will be public or private.\n"
+    printf "    Determines whether your gist will be public or private.\n"
     echo
-    
+
+    # :flag.usage
+    echo "  --id ID"
+    printf "    Specify the UUID of a previous gist you have ownership of and baste will\n    append content to it.\n"
+    echo
+
     # :flag.usage
     echo "  --clipboard, --clip"
-    printf "    Attempts to use the latest entry in your local clipboard as content for your\n    Gist. If using MacOS, an attempt to use pbpaste will be made. Otherwise,\n    xclip will be used.\n"
+    printf "    Attempts to use the latest entry in your local clipboard as content for your\n    gist. If using MacOS, an attempt to use pbpaste will be made. Otherwise,\n    xclip will be used.\n"
     echo
-    
-    # :flag.usage
-    echo "  --skip-short-url"
-    printf "    Resulting Gist URLs are shortened by default using git.io. This flag will\n    skip this entirely and provide the full URL.\n"
-    echo
-    
+
     # :flag.usage
     echo "  --file, -f FILE"
-    printf "    A path to the file to upload to Gist.\n"
+    printf "    A path to the file to upload to gist.\n"
     echo
-    
+
     # :flag.usage
     echo "  --extension, -e EXTENSION"
-    printf "    The file extension of the Gist.\n"
+    printf "    The file extension of the gist.\n"
     printf "    Default: txt\n"
     echo
-    
+
     # :flag.usage
     echo "  --token, -t TOKEN"
     printf "    Explicitly specific a personal developer token as an alternative to using\n    the GITHUB_TOKEN environmental variable.\n"
@@ -160,14 +169,14 @@ baste_usage() {
 
     # :command.usage_environment_variables
     printf "Environment Variables:\n"
-    
+
     # :environment_variable.usage
     echo "  GITHUB_TOKEN"
-    printf "    A personal developer token associated with your Github account. You can\n    easily create a new one in the \"Developer Settings\" section under your\n    account settings page. The only permission scope you will need is \"gist\" in\n    order to create new Gists.\n"
+    printf "    A personal developer token associated with your Github account. You can\n    easily create a new one in the \"Developer Settings\" section under your\n    account settings page. The only permission scope you will need is \"gist\" in\n    order to create new gists.\n"
     echo
     # :command.usage_examples
     printf "Examples:\n"
-    
+
     printf "  base --file /path/to/file.txt\n"
     printf "  baste --content '... code ...'\n"
     printf "  baste --name 'README.md' --content '# My Readme' --public\n"
@@ -230,7 +239,8 @@ inspect_args() {
 #
 # Usage:
 # Use any of the functions below to color or format a portion of a string.
-# 
+#
+
 #   echo "before $(red this is red) after"
 #   echo "before $(green_bold this is green_bold) after"
 #
@@ -273,6 +283,11 @@ requires() {
   command -v "${1}" &> /dev/null || err "baste requires '${1}'; exiting ..."
 }
 
+# :src/lib/validations/validate_valid_uuid.sh
+validate_valid_uuid() {
+  [[ "${1}" =~ ^[a-zA-Z0-9]{32}$ ]] || echo -e "$(red_bold [ERR]) UUID must be a 32-character long alphanumeric string; exiting ..."
+}
+
 # :command.command_functions
 
 # :command.parse_requirements
@@ -283,27 +298,26 @@ parse_requirements() {
     version_command
     exit
     ;;
-  
+
   --help | -h )
     long_usage=yes
     baste_usage
     exit
     ;;
-  
+
   esac
   # :command.environment_variables_filter
   # :command.dependencies_filter
   # :command.command_filter
   action="root"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
     # :flag.case
     --description | -d )
-      if [[ $2 ]]; then
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--description]="$2"
         shift
         shift
@@ -312,10 +326,11 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --name | -n )
-      if [[ $2 ]]; then
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--name]="$2"
         shift
         shift
@@ -324,10 +339,11 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --content | -c )
-      if [[ $2 ]]; then
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--content]="$2"
         shift
         shift
@@ -336,28 +352,40 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --public | -p )
       args[--public]=1
       shift
       ;;
-  
+
+    # :flag.case
+    --id )
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
+        if [[ -n $(validate_valid_uuid "$2") ]]; then
+          printf "validation error in %s:\n%s\n" "--id ID" "$(validate_valid_uuid "$2")"
+          exit 1
+        fi
+        args[--id]="$2"
+        shift
+        shift
+      else
+        printf "%s\n" "--id requires an argument: --id ID"
+        exit 1
+      fi
+      ;;
+
     # :flag.case
     --clipboard | --clip )
       args[--clipboard]=1
       shift
       ;;
-  
-    # :flag.case
-    --skip-short-url )
-      args[--skip-short-url]=1
-      shift
-      ;;
-  
+
     # :flag.case
     --file | -f )
-      if [[ $2 ]]; then
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--file]="$2"
         shift
         shift
@@ -366,10 +394,11 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --extension | -e )
-      if [[ $2 ]]; then
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--extension]="$2"
         shift
         shift
@@ -378,10 +407,11 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --token | -t )
-      if [[ $2 ]]; then
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--token]="$2"
         shift
         shift
@@ -390,21 +420,22 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
-  
+
     -* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
-  
+
     * )
       # :command.parse_requirements_case
       printf "invalid argument: %s\n" "$key"
       exit 1
       ;;
-  
+
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   [[ -n ${args[--name]} ]] || args[--name]="gistfile1"
@@ -417,11 +448,6 @@ initialize() {
   version="0.1.0"
   long_usage=''
   set -e
-
-  if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-    printf "bash version 4 or higher is required\n"
-    exit 1
-  fi
 
   # :src/initialize.sh
   # Code here runs inside the initialize() function
